### ISSUE TITLE
Unde se face trimiterea?

### ISSUE THREAD

**Issue by necenzurat** [memelea/opensms#16]
Am vazut ca nu mai folosesti gammu, unde se trimite efectiv?

**Comment by memelea** [comment]
este tot gammu, dar nu mai folosesc sistemul de fisiere pentru mesaje ci sistemul mysql: http://wammu.eu/docs/manual/smsd/mysql.html

am optat pentru mysql pentru a nu se pierde niciun mesaj in cazul in care serverul cu gammu este picat.
