### ISSUE TITLE
diacritice in SMS

### ISSUE THREAD

**Issue by memelea** [memelea/opensms#5]
in loc de diacritice apar semne de intrebare

**Comment by necenzurat** [comment]
din cate vad, trebuie sa faci coversia pe 7-bit GSM o mica cautare pe google rezulta:

https://en.wikipedia.org/wiki/GSM_03.38

http://michaelsanford.com/php-regex-for-gsm-7-03-38/

https://adywicaksono.wordpress.com/2009/12/24/function-convert8bitto7bit-with-php/
